### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by comiren** [XyHK-HUC/Serv00-Reg#1]
一直显示 发生异常: module 'PIL.Image' has no attribute 'ANTIALIAS', 正在重新开始任务...
大佬这是什么情况
大佬能帮忙注册一下吗

**Comment by XyHK-HUC** [comment]
验证码图片错误

**Comment by illay0569** [comment]
The error AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS' indicates that in newer versions of Pillow (from version 10 onwards), the ANTIALIAS attribute has been removed. From newer versions onwards, you should use Image.Resampling.LANCZOS instead of Image.ANTIALIAS.
